### PR TITLE
Let systemd unit file use /etc/sysconfig/munge for munge options

### LINKED ISSUE #64: specify daemon options with systemd unit file
Hi!

Since the `sysconfig` file has been removed in commit d034b3af731a6f0b937d71896cb87066d9680b13 and the systemd unit file doesn't seem to look at any configuration file, what's the recommend way to pass arguments to the `munged` daemon now? Typically, `--num-threads`.

The `DAEMON_ARGS` variable mentioned in the [`QUICKSTART`](https://github.com/dun/munge/blob/master/QUICKSTART#L127) doesn't seem to apply anymore.

Thanks!

### PR DESCRIPTION
**Pull request by wpoely86**
Fixes #64 

This allows you to cleanly specify options to munged. No need to change a unit file.

### CODE REVIEW

**Comment by dun** [comment]
Thanks for the PR.  The main issue I see here is that Red Hat and SUSE use `/etc/sysconfig`, but Debian and Ubuntu use `/etc/default`.

Aside from that, the current "sysconfig" file specifies vars for NICE, USER, and GROUP which would have no effect in a systemd configuration.  That means I should really have separate template files for sysvinit and systemd.  And then the RPM specfile needs to be updated to install the correct template. A lot of this is dependent upon the autotools rework that has yet to be pulled into master, so I'll finish this up once that work is merged.

**Comment by kkm000** [comment]
> The main issue I see here is that Red Hat and SUSE use `/etc/sysconfig`, but Debian and Ubuntu use `/etc/default`.

An (arguably ugly) workaround to unify the two is
```
EnvironmentFile=-/etc/sysconfig/munge
EnvironmentFile=-/etc/default/munge
```
The `-` prefix is to ignore a missing file.

**Comment by dun** [comment]
@kkm000: But that approach doesn't handle the differences between sysvinit and systemd (i.e., where the latter doesn't use NICE, USER, and GROUP). I'm hoping to do something a bit cleaner in the near future.

**Comment by kkm000** [comment]
@dun, true, the init scripts would not use them.

**Comment by wpoely86** [comment]
@dun Any plans for a version update of munge? Now this change and #23 are merged, it would be helpful to have a proper release.

**Comment by dun** [comment]
@wpoely86 Yes, 0.5.14 should be out in the next couple of weeks. Just wrapping up a few minor things. Among them, revisiting #23 to probably remove the restriction requiring the `--origin` arg to match an address assigned to a local network interface.

**Pull request closed without merging**
